// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -destination=mock/usecase.go -source=usecase.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	input "go-ddd-template/internal/usecase/input"
	output "go-ddd-template/internal/usecase/output"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateUser is a mock of CreateUser interface.
type MockCreateUser struct {
	ctrl     *gomock.Controller
	recorder *MockCreateUserMockRecorder
	isgomock struct{}
}

// MockCreateUserMockRecorder is the mock recorder for MockCreateUser.
type MockCreateUserMockRecorder struct {
	mock *MockCreateUser
}

// NewMockCreateUser creates a new mock instance.
func NewMockCreateUser(ctrl *gomock.Controller) *MockCreateUser {
	mock := &MockCreateUser{ctrl: ctrl}
	mock.recorder = &MockCreateUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateUser) EXPECT() *MockCreateUserMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateUser) Execute(ctx context.Context, in *input.CreateUser) (*output.CreateUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*output.CreateUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateUserMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateUser)(nil).Execute), ctx, in)
}

// MockGetUser is a mock of GetUser interface.
type MockGetUser struct {
	ctrl     *gomock.Controller
	recorder *MockGetUserMockRecorder
	isgomock struct{}
}

// MockGetUserMockRecorder is the mock recorder for MockGetUser.
type MockGetUserMockRecorder struct {
	mock *MockGetUser
}

// NewMockGetUser creates a new mock instance.
func NewMockGetUser(ctrl *gomock.Controller) *MockGetUser {
	mock := &MockGetUser{ctrl: ctrl}
	mock.recorder = &MockGetUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUser) EXPECT() *MockGetUserMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetUser) Execute(ctx context.Context, in *input.GetUser) (*output.GetUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*output.GetUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetUserMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetUser)(nil).Execute), ctx, in)
}

// MockListUsers is a mock of ListUsers interface.
type MockListUsers struct {
	ctrl     *gomock.Controller
	recorder *MockListUsersMockRecorder
	isgomock struct{}
}

// MockListUsersMockRecorder is the mock recorder for MockListUsers.
type MockListUsersMockRecorder struct {
	mock *MockListUsers
}

// NewMockListUsers creates a new mock instance.
func NewMockListUsers(ctrl *gomock.Controller) *MockListUsers {
	mock := &MockListUsers{ctrl: ctrl}
	mock.recorder = &MockListUsersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListUsers) EXPECT() *MockListUsersMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListUsers) Execute(ctx context.Context, in *input.ListUsers) (*output.ListUsers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*output.ListUsers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListUsersMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListUsers)(nil).Execute), ctx, in)
}

// MockUpdateUser is a mock of UpdateUser interface.
type MockUpdateUser struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateUserMockRecorder
	isgomock struct{}
}

// MockUpdateUserMockRecorder is the mock recorder for MockUpdateUser.
type MockUpdateUserMockRecorder struct {
	mock *MockUpdateUser
}

// NewMockUpdateUser creates a new mock instance.
func NewMockUpdateUser(ctrl *gomock.Controller) *MockUpdateUser {
	mock := &MockUpdateUser{ctrl: ctrl}
	mock.recorder = &MockUpdateUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateUser) EXPECT() *MockUpdateUserMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateUser) Execute(ctx context.Context, in *input.UpdateUser) (*output.UpdateUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*output.UpdateUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateUserMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateUser)(nil).Execute), ctx, in)
}

// MockDeleteUser is a mock of DeleteUser interface.
type MockDeleteUser struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteUserMockRecorder
	isgomock struct{}
}

// MockDeleteUserMockRecorder is the mock recorder for MockDeleteUser.
type MockDeleteUserMockRecorder struct {
	mock *MockDeleteUser
}

// NewMockDeleteUser creates a new mock instance.
func NewMockDeleteUser(ctrl *gomock.Controller) *MockDeleteUser {
	mock := &MockDeleteUser{ctrl: ctrl}
	mock.recorder = &MockDeleteUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteUser) EXPECT() *MockDeleteUserMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteUser) Execute(ctx context.Context, in *input.DeleteUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteUserMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteUser)(nil).Execute), ctx, in)
}
