// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"github.com/gin-gonic/gin"
	"github.com/longntv/go-ddd-template/internal/domain/gateway"
	"github.com/longntv/go-ddd-template/internal/handler/health"
	"github.com/longntv/go-ddd-template/internal/handler/http"
	"github.com/longntv/go-ddd-template/internal/handler/http/middleware"
	"github.com/longntv/go-ddd-template/internal/handler/http/server"
	"github.com/longntv/go-ddd-template/internal/infrastructure/datastore"
	"github.com/longntv/go-ddd-template/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeServer builds the real HTTP router for integration tests.
//
// Unlike internal/registry, external dependencies are parameters: the test
// passes its own database and a fast password hasher, so the whole stack from
// router to Postgres runs for real without AWS. Events stop at the outbox
// table; the outbox relay has its own tests in the datastore package.
func InitializeServer(gormDB *gorm.DB, passwordHasher gateway.PasswordHasher) (*gin.Engine, error) {
	userCommandsGateway := datastore.NewUserWriter(gormDB)
	userQueriesGateway := datastore.NewUserReader(gormDB)
	transactor := datastore.NewTransactor(gormDB)
	eventOutbox := datastore.NewEventOutbox(gormDB)
	createUser := service.NewCreateUser(userCommandsGateway, userQueriesGateway, passwordHasher, transactor, eventOutbox)
	getUser := service.NewGetUser(userQueriesGateway)
	listUsers := service.NewListUsers(userQueriesGateway)
	updateUser := service.NewUpdateUser(userCommandsGateway, userQueriesGateway, passwordHasher, transactor, eventOutbox)
	deleteUser := service.NewDeleteUser(userCommandsGateway, userQueriesGateway, transactor, eventOutbox)
	handler := server.NewHandler(createUser, getUser, listUsers, updateUser, deleteUser)
	healthHandler := health.NewHealthHandler()
	corsConfig := _wireCORSConfigValue
	engine := http.Router(handler, healthHandler, corsConfig)
	return engine, nil
}

var (
	_wireCORSConfigValue = middleware.CORSConfig{}
)
