// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"github.com/gin-gonic/gin"
	"github.com/longntv/go-ddd-template/internal/config"
	cloudevents2 "github.com/longntv/go-ddd-template/internal/handler/cloudevents"
	"github.com/longntv/go-ddd-template/internal/handler/health"
	"github.com/longntv/go-ddd-template/internal/handler/http"
	"github.com/longntv/go-ddd-template/internal/handler/http/server"
	"github.com/longntv/go-ddd-template/internal/infrastructure/aws"
	"github.com/longntv/go-ddd-template/internal/infrastructure/aws/sns"
	"github.com/longntv/go-ddd-template/internal/infrastructure/aws/sqs"
	"github.com/longntv/go-ddd-template/internal/infrastructure/cloudevents"
	"github.com/longntv/go-ddd-template/internal/infrastructure/datastore"
	"github.com/longntv/go-ddd-template/internal/service"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// InitializeServer initializes the HTTP server with the necessary dependencies.
func InitializeServer(cfg *config.Config, logger *zap.Logger) (*gin.Engine, func(), error) {
	db, err := datastore.NewDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	gormDB := datastore.ProvideGormDB(db)
	userCommandsGateway := datastore.NewUserWriter(gormDB)
	userQueriesGateway := datastore.NewUserReader(gormDB)
	awsConfig, err := aws.LoadConfig(cfg)
	if err != nil {
		return nil, nil, err
	}
	client := sns.NewClient(awsConfig)
	publisher := sns.NewPublisherFromConfig(client, cfg)
	cloudeventsPublisher := cloudevents.NewPublisher(publisher)
	createUser := service.NewCreateUser(userCommandsGateway, userQueriesGateway, cloudeventsPublisher)
	getUser := service.NewGetUser(userQueriesGateway)
	listUsers := service.NewListUsers(userQueriesGateway)
	updateUser := service.NewUpdateUser(userCommandsGateway, userQueriesGateway, cloudeventsPublisher)
	deleteUser := service.NewDeleteUser(userCommandsGateway, userQueriesGateway, cloudeventsPublisher)
	handler := server.NewHandler(createUser, getUser, listUsers, updateUser, deleteUser)
	healthHandler := health.NewHealthHandler()
	engine := http.Router(handler, healthHandler)
	return engine, func() {
	}, nil
}

// InitializeSubscriber initializes the CloudEvents subscriber with the
// necessary dependencies.
func InitializeSubscriber(cfg *config.Config, logger *zap.Logger) (*cloudevents.Subscriber, func(), error) {
	awsConfig, err := aws.LoadConfig(cfg)
	if err != nil {
		return nil, nil, err
	}
	client := sqs.NewClient(awsConfig)
	subscriber := sqs.NewSubscriberFromConfig(client, cfg)
	handler := cloudevents2.NewHandler()
	mux := cloudevents.ProvideConfiguredMux(handler)
	cloudeventsSubscriber := cloudevents.NewSubscriber(subscriber, mux, logger)
	return cloudeventsSubscriber, func() {
	}, nil
}
