// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -destination=mock/user.go -source=user.go
//

// Package mock_gateway is a generated GoMock package.
package mock_gateway

import (
	context "context"
	entity "go-ddd-template/internal/domain/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBinder is a mock of Binder interface.
type MockBinder struct {
	ctrl     *gomock.Controller
	recorder *MockBinderMockRecorder
	isgomock struct{}
}

// MockBinderMockRecorder is the mock recorder for MockBinder.
type MockBinderMockRecorder struct {
	mock *MockBinder
}

// NewMockBinder creates a new mock instance.
func NewMockBinder(ctrl *gomock.Controller) *MockBinder {
	mock := &MockBinder{ctrl: ctrl}
	mock.recorder = &MockBinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinder) EXPECT() *MockBinderMockRecorder {
	return m.recorder
}

// Bind mocks base method.
func (m *MockBinder) Bind(ctx context.Context) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bind", ctx)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Bind indicates an expected call of Bind.
func (mr *MockBinderMockRecorder) Bind(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bind", reflect.TypeOf((*MockBinder)(nil).Bind), ctx)
}

// MockUserQueriesGateway is a mock of UserQueriesGateway interface.
type MockUserQueriesGateway struct {
	ctrl     *gomock.Controller
	recorder *MockUserQueriesGatewayMockRecorder
	isgomock struct{}
}

// MockUserQueriesGatewayMockRecorder is the mock recorder for MockUserQueriesGateway.
type MockUserQueriesGatewayMockRecorder struct {
	mock *MockUserQueriesGateway
}

// NewMockUserQueriesGateway creates a new mock instance.
func NewMockUserQueriesGateway(ctrl *gomock.Controller) *MockUserQueriesGateway {
	mock := &MockUserQueriesGateway{ctrl: ctrl}
	mock.recorder = &MockUserQueriesGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserQueriesGateway) EXPECT() *MockUserQueriesGatewayMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockUserQueriesGateway) Exists(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockUserQueriesGatewayMockRecorder) Exists(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockUserQueriesGateway)(nil).Exists), ctx, email)
}

// Get mocks base method.
func (m *MockUserQueriesGateway) Get(ctx context.Context, id entity.UserID) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserQueriesGatewayMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserQueriesGateway)(nil).Get), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockUserQueriesGateway) GetByEmail(ctx context.Context, email string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserQueriesGatewayMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserQueriesGateway)(nil).GetByEmail), ctx, email)
}

// List mocks base method.
func (m *MockUserQueriesGateway) List(ctx context.Context, limit, offset int) ([]*entity.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]*entity.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockUserQueriesGatewayMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserQueriesGateway)(nil).List), ctx, limit, offset)
}

// MockUserCommandsGateway is a mock of UserCommandsGateway interface.
type MockUserCommandsGateway struct {
	ctrl     *gomock.Controller
	recorder *MockUserCommandsGatewayMockRecorder
	isgomock struct{}
}

// MockUserCommandsGatewayMockRecorder is the mock recorder for MockUserCommandsGateway.
type MockUserCommandsGatewayMockRecorder struct {
	mock *MockUserCommandsGateway
}

// NewMockUserCommandsGateway creates a new mock instance.
func NewMockUserCommandsGateway(ctrl *gomock.Controller) *MockUserCommandsGateway {
	mock := &MockUserCommandsGateway{ctrl: ctrl}
	mock.recorder = &MockUserCommandsGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCommandsGateway) EXPECT() *MockUserCommandsGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserCommandsGateway) Create(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserCommandsGatewayMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserCommandsGateway)(nil).Create), ctx, user)
}

// Delete mocks base method.
func (m *MockUserCommandsGateway) Delete(ctx context.Context, id entity.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserCommandsGatewayMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserCommandsGateway)(nil).Delete), ctx, id)
}

// Update mocks base method.
func (m *MockUserCommandsGateway) Update(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserCommandsGatewayMockRecorder) Update(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserCommandsGateway)(nil).Update), ctx, user)
}
