package datastore

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"

	"github.com/longntv/go-ddd-template/internal/domain/event"
)

// OutboxEventEntity represents the outbox_events table.
type OutboxEventEntity struct {
	ID            uuid.UUID  `gorm:"type:uuid;primary_key"`
	Seq           int64      `gorm:"->"` // generated by the database
	Type          string     `gorm:"type:varchar(255);not null"`
	Source        string     `gorm:"type:varchar(255);not null"`
	Subject       string     `gorm:"type:varchar(255);not null;default:''"`
	Data          []byte     `gorm:"type:jsonb;not null"`
	OccurredAt    time.Time  `gorm:"type:timestamptz(3);not null"`
	Attempts      int        `gorm:"not null;default:0"`
	NextAttemptAt time.Time  `gorm:"type:timestamptz(3);not null;default:CURRENT_TIMESTAMP(3)"`
	LastError     string     `gorm:"type:text;not null;default:''"`
	PublishedAt   *time.Time `gorm:"type:timestamptz(3)"`
}

// TableName specifies the table name for OutboxEventEntity.
func (OutboxEventEntity) TableName() string {
	return "outbox_events"
}

// newOutboxEventEntity converts a domain event to a pending outbox row. Its
// first attempt is due at once: NextAttemptAt stays zero so the database
// default (its own clock) applies.
func newOutboxEventEntity(evt *event.DomainEvent) (*OutboxEventEntity, error) {
	data, err := json.Marshal(evt.Data)
	if err != nil {
		return nil, fmt.Errorf("encode %s event data: %w", evt.Type, err)
	}
	return &OutboxEventEntity{
		ID:         evt.ID,
		Type:       evt.Type,
		Source:     evt.Source,
		Subject:    evt.Subject,
		Data:       data,
		OccurredAt: evt.Timestamp,
	}, nil
}

// ToDomain converts the row back to the event it stores. Data is the stored
// JSON, published as is; an event saved without data gets none back.
func (e *OutboxEventEntity) ToDomain() *event.DomainEvent {
	evt := &event.DomainEvent{
		ID:        e.ID,
		Type:      e.Type,
		Source:    e.Source,
		Subject:   e.Subject,
		Timestamp: e.OccurredAt,
	}
	if string(e.Data) != "null" {
		evt.Data = json.RawMessage(e.Data)
	}
	return evt
}
